[package]
name = "bevy_html_lite"
version = "0.3.0"
edition = "2024"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false }
html_lite_macros = { version = "0.2.1", path = "html_lite_macros" }
html_lite_sections = { version = "0.2.1", path = "html_lite_sections" }
itertools = "0.14.0"

[dev-dependencies]
bevy = { workspace = true, default-features = true }

[workspace]
members = [ "html_lite_sections", "html_lite_macros", "examples/*" ]

[workspace.dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false, features = [ "reflect_auto_register" ] }

[features]
default = [ "plugin" ]
plugin = [ "bevy/default_font", "bevy/bevy_asset", "bevy/bevy_color", "bevy/bevy_text", "bevy/bevy_ui" ]
